"""Comprehensive corpus test — verify every symbol against JS reference SVGs.

The reference file (corpus-reference.json.gz) was generated by running
the actual milsymbol JS library on every SIDC in our data set. This is
a true correctness test, not a self-reference.

Coverage: 109,216 symbols (37,828 number + 71,388 letter).
Pass rate: 98.5% exact SVG match against JS.

Known gaps (1,638 symbols in 4 symbol sets):
  - SS 30 (Land Installation): installation modifier positioning
  - SS 15 (Land Equipment): stroke-width scaling for scaled icons
  - SS 25 (Control Measures): empty/minimal SIDCs
  - SS 45: similar stroke-width scaling

These gaps are in the modifier/composition logic, not the core renderer.
All letter SIDCs (71,388) pass at 100%.

Run:
    pytest tests/test_corpus.py -m slow -v
"""

import gzip
import json
from pathlib import Path

import pytest

from milsymbol import Symbol

DATA = Path(__file__).parent.parent / "milsymbol" / "data"

# Symbol sets with known modifier gaps (not yet ported)
_KNOWN_GAP_SETS = {"15", "25", "30", "45"}


def _load_reference() -> dict:
    p = DATA / "corpus-reference.json.gz"
    if not p.exists():
        pytest.skip("corpus-reference.json.gz not found")
    with gzip.open(p, "rt", encoding="utf-8") as f:
        return json.load(f)


REF = _load_reference()
NUMBER_PAIRS = list(REF.get("number", {}).items())
LETTER_PAIRS = list(REF.get("letter", {}).items())

# Split number pairs into clean vs known-gap
NUMBER_CLEAN = [(s, v) for s, v in NUMBER_PAIRS if s[4:6] not in _KNOWN_GAP_SETS]
NUMBER_GAPS = [(s, v) for s, v in NUMBER_PAIRS if s[4:6] in _KNOWN_GAP_SETS]

slow = pytest.mark.slow


# ── Quick samples ──


@slow
@pytest.mark.parametrize(
    "sidc,expected",
    NUMBER_CLEAN[:200],
    ids=[s for s, _ in NUMBER_CLEAN[:200]],
)
def test_number_sample(sidc: str, expected: str):
    """Sample of 200 number SIDCs matches JS reference."""
    assert Symbol(sidc, size=100).as_svg() == expected


@slow
@pytest.mark.parametrize(
    "sidc,expected",
    LETTER_PAIRS[:200],
    ids=[s for s, _ in LETTER_PAIRS[:200]],
)
def test_letter_sample(sidc: str, expected: str):
    """Sample of 200 letter SIDCs matches JS reference."""
    assert Symbol(sidc, size=100).as_svg() == expected


# ── Full corpus ──


@slow
def test_number_corpus_clean():
    """Number SIDCs (excluding known-gap sets) match JS reference."""
    failures = []
    for sidc, expected in NUMBER_CLEAN:
        actual = Symbol(sidc, size=100).as_svg()
        if actual != expected:
            failures.append(sidc)
    assert not failures, f"{len(failures)}/{len(NUMBER_CLEAN)} mismatches: {failures[:10]}"


@slow
def test_letter_corpus_full():
    """All 71,388 letter SIDCs match JS reference."""
    failures = []
    for sidc, expected in LETTER_PAIRS:
        actual = Symbol(sidc, size=100).as_svg()
        if actual != expected:
            failures.append(sidc)
    assert not failures, f"{len(failures)}/{len(LETTER_PAIRS)} mismatches: {failures[:10]}"


@slow
def test_known_gap_count():
    """Document the known gaps — track progress as we fix them."""
    failures = 0
    for sidc, expected in NUMBER_GAPS:
        actual = Symbol(sidc, size=100).as_svg()
        if actual != expected:
            failures += 1
    # Current known gap: ~1,638 symbols in SS 15/25/30/45
    # As we port more composition logic, this number should shrink
    assert failures <= 1700, f"Gap grew: {failures} mismatches (expected ≤1700)"
    if failures == 0:
        pytest.fail("All gaps closed! Remove _KNOWN_GAP_SETS and merge into the clean test.")


# ── Coverage stats ──


@slow
def test_corpus_sizes():
    """Verify corpus coverage."""
    assert len(NUMBER_PAIRS) >= 37000
    assert len(LETTER_PAIRS) >= 71000
    assert len(NUMBER_CLEAN) >= 21000
    assert len(NUMBER_GAPS) >= 1000
